export const USPESNO_REGISTROVAN = 'USPESNO_REGISTROVAN';
export const GRESKA_PRILIKOM_REGISTROVANJA = 'GRESKA_PRILIKOM_REGISTROVANJA';
export const USPESNO_LOGOVAN = 'USPESNO_LOGOVAN';
export const GRESKA_PRI_LOGOVANJU = 'GRESKA_PRI_LOGOVANJU';
