export const USPESNO_REGISTROVAN = 'USPESNO_REGISTROVAN';
export const GRESKA_PRILIKOM_REGISTROVANJA = 'GRESKA_PRILIKOM_REGISTROVANJA';
export const USPESNO_LOGOVAN = 'USPESNO_LOGOVAN';
export const GRESKA_PRI_LOGOVANJU = 'GRESKA_PRI_LOGOVANJU';
export const USPESNO_REGISTROVANA_ORDINACIJA =
  'USPESNO_REGISTROVANA_ORDINACIJA';
export const GRESKA_PRILIKOM_REGISTROVANJA_ORDINACIJE =
  'GRESKA_PRILIKOM_REGISTROVANJA_ORDINACIJE';
export const POSTAVI_ORDINACIJU = 'POSTAVI_ORDINACIJU';
export const LOGOUT = 'LOGOUT';
export const SVI_ZUBARI = 'SVI_ZUBARI';
export const SVI_KORISNICI = 'SVI_KORISNICI';
export const SVI_STUDENTI = 'SVI_STUDENTI';
export const SVE_PORUKE = 'SVE_PORUKE';
